
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cesltdnpizhouatyezok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlc2x0ZG5waXpob3VhdHllem9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjk1NTcsImV4cCI6MjA2MDQwNTU1N30.DjOCADrR_JQ0cGoE69CJxBY69dIZdRX1PdL7vEJktNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage,
      flowType: 'pkce',
      detectSessionInUrl: true
    }
  }
);

// Removed automatic GitHub OAuth initialization
